a=open("a1.txt","w")
a.write("abc de\nfg hij\nklmnop qr")
a.close()
b=open("a1.txt","r")
l1=b.read(3)
print(l1)
tx1=b.read(5)
print(tx1)
print("RESULT IS:",b.tell())
b.seek(0)
print(b.read(2))
print("RESULT IS:",b.tell())
b.close()